/'
This is a small example employing the plantuml library for Petri Nets.

It illustrateds the definition of a simple yet colorful petri net.
**Note:** This library currently falls back to graphviz, hence all style options are provided via graphviz options rather than plantuml options.

Author: Eden_06 <thomas.eden06.kuehn@googlemail.com>
Created on: 2023-04-12
Website: 
License: MIT Licence
'/
@startuml
!include ../plantuml-petrinets.iuml

digraph PTnet {

  LeftToRight()

  VTrans(Sub("t0"),t0)
  Place(Sub("s0"),s0,_marking=Token(2))
  VTrans(Sub("t1"),t1,_style="fillcolor=red")
  Place(Sub("s1"),s1)

  Arc(t0,s0)
  Arc(s0,t1,"2")
  Arc(t1,s1)
  ArcHidden(s0,s1)

}

@enduml
