/'
This is a small example employing the plantuml library for Petri Nets.

It illustrateds the definition of a simple yet colorful petri net.
**Note:** This library currently falls back to graphviz, hence all style options are provided via graphviz options rather than plantuml options.

Author: Eden_06 <thomas.eden06.kuehn@googlemail.com>
Created on: 2023-04-12
Website: 
License: MIT Licence
'/
@startuml
!include ../plantuml-petrinets.iuml

digraph PTnet {

  LeftToRight()

  VTrans(t0)
  Place(p0,_marking=Token(2))
  VTrans(t1)
  Place(p1)

  Arc(t0,p0)
  Arc(p0,t1,"2")
  Arc(t1,p1)

}

@enduml
