/'
This is a small example employing the plantuml library for Petri Nets.

It illustrateds the definition of a simple yet colorful petri net.
**Note:** This library currently falls back to graphviz, hence all style options are provided via graphviz options rather than plantuml options.

Author: Eden_06 <thomas.eden06.kuehn@googlemail.com>
Created on: 2023-04-12
Website: 
License: MIT Licence
'/
@startuml
!include ../plantuml-petrinets.iuml

digraph PTnet {

  LeftToRight()

  %set_variable_value("_placeStyle", "style=filled, fillcolor=yellow")
  %set_variable_value("_transStyle", "fillcolor=blue")

  Place(p1,_marking=Token(2))
  VTrans(t1,_style="fillcolor=red")
  Place("P 2",p2,_style="fillcolor=green")
  VTrans(t2,"")
  Place(p3,_marking=Token())

  Arc(p1,t1,"2")
  Arc(t1,p2)
  Arc(p2,t2)
  ArcUp(t2,p3)
  ArcUp(p3,t1)
}

@enduml
